### ISSUE TITLE
Import Data.json

### ISSUE THREAD

**Issue by rdiezv** [cogniteev/oncrawl-elk#16]
Hi, there's a way to import the dashboard to a previous ELK installation? (not based on oncrawl-elk)
Kind regards

**Comment by tuxnco** [comment]
Hi @rdiezv,

Thanks for your interest.

Have a look at these:
- Kibana config data: https://github.com/cogniteev/oncrawl-elk/blob/master/recipes/kibana-config/data.json
- Kibana mapping: https://github.com/cogniteev/oncrawl-elk/blob/master/recipes/kibana-config/mapping.json
- Logstash conf: https://github.com/cogniteev/oncrawl-elk/tree/master/recipes/logstash/conf

Even if you work with a previous installation, you would have to reindex the data with the updated logstash settings so that proper fields a processed to elasticsearch (bot hits, seo visits)

HTH, closing for now.
