### ISSUE TITLE
Add a way to inject log messages without using files (id. TCP/UDP streams)

### ISSUE THREAD

**Issue by C-Duv** [cogniteev/oncrawl-elk#5]
Logstash supports a stream (TCP or UDP) input, it could be useful to support such non-file input in this application. This allows running the OnCrawl app on a different server than the web server.

**Comment by tristan0x** [comment]
Hi @C-Duv ! Thanks for your interest.

As Logstash provides dozens of different inputs, I am not sure supporting several sources scale at long term. Logstash configuration will become complex. vicious, and the solution won't be plug'n play anymore.

Furthermore oncrawl-elk 1.0 only uses 1 Elasticsearch node meaning that you can't push billions of logs. This is why it is recommended in the documentation to extract a subset of your logs and copy them to the server where oncrawl-elk will be installed.

Maybe one day, if oncrawl-elk supports an Elasticsearch cluster, I guess the current solution will be split in 2 _almost_ plug'n play components:
- logstash: installed on every monitored web servers, pushing logs to the Elasticsearch cluster
- swarm / kubernetes cluster: managing Kibana and Elasticsearch nodes

In the meantime, if you want to have both real-time monitoring of your webserver and install Elasticsearch/Kibana on another server, I suggest you to fork oncrawl-elk and hack it a little bit to split the `docker-compose.yml` in 2 different applications exactly like I explained above: a logstash container deployed on your web server pushing logs to an Elasticsearch container linked to another Kibana container, both running on another server :
1. Split the `docker-compose.yml` in 2 different files
2. Remove the `link` between Elasticsearch and Logstash containers
3. Expose the Elasticsearch container ports so that their are mapped to ports on the host. Elasticsearch will be isolated in the container and Logstash won't be able to contact it.
4. Replace the `hosts` parameter of logstash Elasticsearch output so that it pushes to the server where is running the Elasticsearch container.

We can provide you support if you need. And of course, pull-requests are welcome :)
Cheers

**Comment by C-Duv** [comment]
I understand the "data subset use case" and I'm fine with that. What I want to avoid is copying .log files from a server to another: it uses disk space on _oncrawl-elk server_ as (uncompressed) files AND on the ElasticSearch server's data directory.
I'm sure once _oncrawl-elk server_ has noticed and processed the files I can delete them (didn't checked though) but I can't be sure when I can actually do it (there is no process progress information/bar).

If, instead of copying log files into a given apache/iis/nginx directory, I could send them over the wire on a given port (one for each server) it would works just as fine and would require less work.
It could also lead to a system where a user can enable/disable realtime log-streaming via it's administration interface (my job to create that for him) when he wants (by this, he creates the subset on it's own) and goes to the always running _oncrawl-elk server_ instance.
All this without requiring any action (`scp`, _wait_, `ssh rm`) from operation team.

Here is what I had in mind:

``` Patch
diff --git a/recipes/logstash/conf/logstash.conf b/recipes/logstash/conf/logstash.conf
index 60c60ba..5ccb6bb 100644
--- a/recipes/logstash/conf/logstash.conf
+++ b/recipes/logstash/conf/logstash.conf
@@ -4,16 +4,40 @@ input {
                 'type' => 'apache'
                 'start_position' => 'beginning'
         }
+        tcp {
+            port => 9001
+            type => 'apache'
+        }
+        udp {
+            port => 9001
+            type => 'apache'
+        }
         file {
                 'path' => '/logs/nginx/*.log'
                 'type' => 'nginx'
                 'start_position' => 'beginning'
         }
+        tcp {
+            port => 9002
+            type => 'nginx'
+        }
+        udp {
+            port => 9002
+            type => 'nginx'
+        }
         file {
                'path' => '/logs/iis/*.log'
                 'type' => 'iis'
                 'start_position' => 'beginning'
         }
+        tcp {
+            port => 9003
+            type => 'iis'
+        }
+        udp {
+            port => 9003
+            type => 'iis'
+        }

 }
```

Please note that I'm not trying to send **realtiem** log events from production web server, but only a date range of .log.gz files from production server to _oncrawl-elk server_ without the hassle of copying files over.

**Comment by phildav** [comment]
Hi @C-Duv,
we have a handful number of options to avoid copying the log files from the webserver to the _oncrawl-elk_ server:
- as you mentionned, we can open a port where logstash listens to. Then we will need to configure either [logstash forwarder](https://github.com/elastic/logstash-forwarder) or [rsyslog](http://www.freeipa.org/page/Howto/Centralised_Logging_with_Logstash/ElasticSearch/Kibana) on the web server(s) to push the event logs
- we can also share the log directory in read only to the _oncrawl-elk_ server
- If we dig into the direction of copying log files to the _oncrawl-elk_ server, I'm sure it's not too hard to write a script that remove the raw log files **safely** once they are fully read by logstash.

At that point I think we could write some guidelines and sample configuration files about the main options to feed logstash, and let people decide which path they want to take. But as @tristan0x there are plenty of input plugins available, and that's the beauty of using logstash ;)
